services:
     maple-bot:
          image: ghcr.io/azpepoze/maple:latest
          container_name: maple_bot
          restart: unless-stopped
          env_file:
             - .env
          network_mode: "host"
          ports:
             - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
          volumes:
             - ./data:/app/data

     watchtower:
          image: containrrr/watchtower
          container_name: watchtower
          volumes:
             - /var/run/docker.sock:/var/run/docker.sock
          command: --interval 300 maple_bot
          restart: unless-stopped
