services:
     maple-bot:
          build:
               context: .
               dockerfile: Dockerfile
          container_name: maple_bot
          restart: unless-stopped
          env_file:
               - .env # Load environment variables from .env file
          network_mode: "host"
          ports:
               - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
          volumes:
             - ./data:/app/data
